### ISSUE TITLE
$instance = $launcher->launch( $ctx) hang up with "--remote-debugging-port=9222"

### ISSUE THREAD

**Issue by kikashine** [jakubkulhan/chrome-devtools-protocol#15]
Hi, thanks for the great package.

with  "--remote-debugging-port=9222", it create command line:

exec '/usr/bin/google-chrome' '--headless' '--window-size=1280,1024' '--disable-gpu' '--ignore-certificate-errors' '--no-sandbox' 'user-agent=Mozilla/5.0 (X11; Linux x86_64)AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.39 Safari/537.36' '--remote-debugging-port=9222' '--user-data-dir=/tmp/chrome-profile-39017'

"--remote-debugging-port=9222" and "--user-data-dir=/tmp/chrome-profile-39017"，port number is incorrect.

did i missed something？

thanks for your help.

**Comment by jakubkulhan** [comment]
Hi, if you do not specify port number when creating `Launcher` instance, it generates random port number for the Chrome process being launched. You should specify port for the `Launcher`:

```php
$launcher = new Launcher(9222);
// or
$launcher = new Launcher();
$launcher->setPort(9222);
```

And then you shouldn't set `--remote-debugging-port=...` in `$args`.

I've committed more strict validation of supplied `$args` for `launch()` method that throws an exception when such conflict happens.
