### ISSUE TITLE
printToPDF triggered before ajax request completion

### ISSUE THREAD

**Issue by ranjeshgupta** [jakubkulhan/chrome-devtools-protocol#19]
$ctx = Context::withTimeout(Context::background(), 30);
$chrome_binary_file = '/usr/bin/google-chrome';
$launcher = new Launcher();
$launcher->setExecutable($chrome_binary_file);
$instance = $launcher->launch($ctx, '--user-data-dir=/tmp/chrome-user-data', '--disable-gpu --virtual-time-budget=5000');

$tab = $instance->open($ctx);
$tab->activate($ctx);
$devtools = $tab->devtools();

$devtools->page()->enable($ctx);
$devtools->page()->navigate($ctx, NavigateRequest::builder()->setUrl($source_url)->setReferrer($ref_url)->build());
$devtools->page()->awaitLoadEventFired($ctx);

 $data = $devtools->page()->printToPDF($ctx, PrintToPDFRequest::fromJson((object)[
                                    'displayHeaderFooter' => true,
                                    'paperWidth' => 8.27,
                                    'paperHeight' => 11.69,
                                    'headerTemplate' => '<div style="display: block; width: 100%; text-align: center; font-size: 8px;"><span></span><span class="title"></span></div>',
                                    'footerTemplate' => '<div style="display: block; width: 100%; text-align: right; font-size: 8px; padding-right: 30px;">Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>'
                                ]))->data;

file_put_contents($filename, base64_decode($data))

**Comment by jakubkulhan** [comment]
Hi, @ranjeshgupta! `$devtools->page()->awaitLoadEventFired($ctx);` waits only for document `load` event (i.e. the same as `<body onload="...">`). AJAX requests are asynchronous, therefore `load` event is fired regardless if there's such request in flight.

You might use:

```php
$response = $devtools->runtime()->evaluate($ctx, EvaluateRequest::builder()
    ->setAwaitPromise(true)
    ->setExpression('...')
    ->build()
);
```

With expression (JS code) that returns a promise that fulfils after all requests have finished.

**Comment by ranjeshgupta** [comment]
Thanks a lot. It works
