### ISSUE TITLE
Possible to run multiple tasks with 'daemonized' chrome-headless and CDP?

### ISSUE THREAD

**Issue by typoworx-de** [jakubkulhan/chrome-devtools-protocol#22]
I would like to know if it is possible to run multiple tasks (f.e. PDF generation) using remote-debugging and daemonized chrome-headless (one instance running always in background)?

For every task there could be created a new tab kept open until the task is finished. Is this possible or doesn't it make sense at all?

**Comment by jakubkulhan** [comment]
Hi. Yes, it's possible. It's how we use Chrome in production at @scuk. I suggest you use headless contexts, see https://github.com/jakubkulhan/chrome-devtools-protocol#headless-chrome-isolated-contexts, not tabs, as with tabs you share cookies, caches etc., headless contexts are isolated from each other.
