### ISSUE TITLE
implode() deprecated in PHP 7.4

### ISSUE THREAD

**Issue by yngveo** [jakubkulhan/chrome-devtools-protocol#24]
I have updated my dev environment to PHP 7.4 and am now getting an exception when running Tab->devtools();

The error occurs in Protocol.php line 330 - implode(). 

Error message:

implode(): Passing glue string after array is deprecated. Swap the parameters

**Comment by xsuchy09** [comment]
This is bug in wrench/wrench library (https://github.com/varspool/Wrench/issues/128, https://github.com/varspool/Wrench/pull/129, ...). Now fixed in master but still not new version. So in v2.0.8 there is this deprecated error in wrench/wrench required library. There is wrench v3.0 with fix but it is still not stable ... but maybe update this library to v3.0 can help (but there can be incompatible issues - new major version) ...
```
composer require wrench/wrench ~3.0
```
edit: Yes, there are incompatible issues ...

**Comment by jakubkulhan** [comment]
Hi, I've pushed a new version fix release that depends on PR created by @wells. Hopefully, the fix will be merged soon to the upstream.

**Comment by wells** [comment]
Thanks @jakubkulhan 

Looks like we may be able to get 3.* tagged on wrench with a proper assist to get that across the finish line. Hopefully no breaking changes involved apart from phpunit / php versioning.

**Comment by wells** [comment]
@jakubkulhan, I was able to use dev-master of wrench without issue on php 7.4. This is not a definitive end-to-end test, but I made a forked branch of this package to take a test drive. Let's hope 3.0 of wrench gets tagged soon.

**Comment by kondaurov** [comment]
Hi @jakubkulhan 
Is it possible to wait for a release with a commit [fixes for PHP 7.4](https://github.com/jakubkulhan/chrome-devtools-protocol/commit/933cde97ab8e3c395f167c952327f9f413ca461a) in the near future?

**Comment by jakubkulhan** [comment]
@kondaurov Until Websocket library merges this PR https://github.com/varspool/Wrench/pull/130 and tags a release, I cannot create tagged release here.

**Comment by iwiznia** [comment]
Websocket released [version 2.0](https://github.com/varspool/Wrench/tree/2.0) with [the fix](https://github.com/varspool/Wrench/pull/130) merged. Can we get a release with the dependency updated please?

**Comment by wells** [comment]
I concur. @jakubkulhan can we get a tagged release for this repo, now that v2.0.11 has my pull request merged on wrench? Thanks.

**Comment by jakubkulhan** [comment]
Tagged as https://github.com/jakubkulhan/chrome-devtools-protocol/releases/tag/v1.0.3

**Comment by wells** [comment]
@jakubkulhan You may also want to remove this from your composer.json
```
"repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/wells/Wrench.git"
    }
  ]
```

**Comment by jakubkulhan** [comment]
@wells Good point, thanks! Removed.

**Comment by iwiznia** [comment]
Thank you!!

**Comment by wells** [comment]
Sorry to be a bother. @jakubkulhan, could you either move the `v1.0.3` tag to commit 95fcaa3 or tag a new release?

**Comment by jakubkulhan** [comment]
@wells Sure, tagged as v1.0.4.
