### ISSUE TITLE
Upgrade wrench/wrench dependency to ^2.0.10

### ISSUE THREAD

**Issue by alexander-schreiner-seobility** [jakubkulhan/chrome-devtools-protocol#28]
I am aware of https://github.com/jakubkulhan/chrome-devtools-protocol/issues/25 and this is not a duplicate.

When using this library with PHP 7.4 developers will run into the following: `implode(): Passing glue string after array is deprecated. Swap the parameters`

I've done some research and found that this issue arises from `wrench/wrench` when using PHP 7.4 and is already fixed in `wrench/wrench`: https://github.com/varspool/Wrench/pull/130

The issue got solved with the following release of wrench: https://github.com/varspool/Wrench/releases/tag/v2.0.10

This library should use at least 2.0.10, if not 3.x as suggested in https://github.com/jakubkulhan/chrome-devtools-protocol/issues/25, to make sure it stays usable with PHP 7.4

**Temporary fix**

To temporarly fix this issue require `wrench/wrench` before `jakubkulhan/chrome-devtools-protocol` in your composer.json like so: `"wrench/wrench":` "^2.0.11",`

**Comment by jakubkulhan** [comment]
Dependency was upgraded to 2.0.10 in #24
