### ISSUE TITLE
Allow use in PHP 7.2

### ISSUE THREAD

**Issue by Danack** [jakubkulhan/chrome-devtools-protocol#4]
Hi, 

Does the library work okay in PHP 7.2? If so, would it be possible to change the PHP requirements to be either 

```
"php": "~7.1 | ~7.2",
```
Or
```
"php": "^7.1",
```

Or whatever is best for allowing installing on 7.2 ?

**Comment by jakubkulhan** [comment]
Hi. Yes, it works with 7.2. Requirements use `"php": "~7.1"`, which means `>=7.1 <8.0`, so it should install without problem. I even use it in production running 7.2.

**Comment by Danack** [comment]
Oops, sorry, forgot we had a rogue

    "config": {
        "platform": {
            "php": "7.0"
        }
    }

in our composer.json file.
