### ISSUE TITLE
Make launcher executable configurable

### ISSUE THREAD

**Issue by george-viaud** [jakubkulhan/chrome-devtools-protocol#6]
I'm likely just not seeing the mechanism to do this, but I would like to specify the `chromium-browser` executable as I will not be installing google-chrome unless need-be.

Perhaps just switch out the const and use a setter method?

**Comment by jakubkulhan** [comment]
Hello, George. @mikenz had a similar problem / feature request in #3 As I suggested, either `launchWithExecutable` could be made `public`, or as you propose, use setter to configure custom executable. Would you create PR with the change?

**Comment by jakubkulhan** [comment]
solved by #10
